### ISSUE TITLE
None of the provided jars work on BIMserver 1.2

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/WebGL-threeJS#6]
When trying the 0.2 on the BIMserver 1.2.0 RC7 BIMserver fails to start.

```
18:06:33 ERROR                                                                                  (org.bimserver.BimServer.java:441) 
java.lang.NoSuchMethodError: org.bimserver.plugins.PluginManager.requireIfcEngine()Lorg/bimserver/plugins/ifcengine/IfcEnginePlugin;
    at org.bimserver.serializers.json.JSONModelFormat2SerializerPlugin.init(JSONModelFormat2SerializerPlugin.java:37)
    at org.bimserver.plugins.PluginManager.initAllLoadedPlugins(PluginManager.java:396)
    at org.bimserver.BimServer.start(BimServer.java:301)
```

Seems there is a missing semicolon, breaking the script. I'm interested in picking up the development of this plugin, bringing it to full specification of the current three.js . Any help is welcome.
